export const mockedOrders = [
  {
    id: "1",
    customerName: "John Doe",
    phoneNumber: "123-456-7890",
    email: "john@example.com",
    bikeBrand: "Trek",
    serviceType: "Wheel adjustment",
    dueDate: "01-12-2024",
    notes: "Check the brakes as well",
  },
  {
    id: "2",
    customerName: "Jane Smith",
    phoneNumber: "987-654-3210",
    email: "jane@example.com",
    bikeBrand: "Giant",
    serviceType: "Chain repair",
    dueDate: "10-12-2024",
    notes: "Replace the rear chain",
  },
  {
    id: "3",
    customerName: "Maria Hansen",
    phoneNumber: "984-652-3220",
    email: "maria@example.com",
    bikeBrand: "Giant",
    serviceType: "Brake maintenance",
    dueDate: "01-01-2025",
    notes: "",
  },
];
